apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-xopt
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkwch-fix-0075-0006-tenant/tkwch-fix-0075-0006-app/devfile-sample-xopt@sha256:64e7899ec06b5f94c620ffe8f2f715da0c1df45d6657f7ac050fc776f29e2c29
        name: my-nodejs
        resources: {}
status: {}
